# -*- coding: utf-8 -*-
"""weather_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rStRfvjaKrUBH_NQtX02fPFFYHE9bblO

**Load and inspect data**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('seaborn-v0_8')

# Load data
df = pd.read_csv('/content/weather.csv')

# Quick inspection
print(df.head())
print(df.info())
print(df.describe(include='all'))

"""**Data cleaning**"""

# Rename columns
df = df.rename(columns={"Formatted Date": "date",
    "Temperature (C)": "temp_c",
    "Apparent Temperature (C)": "feels_like_c",
    "Humidity": "humidity",
    "Precip Type": "precip_type",
    "Wind Speed (km/h)": "wind_speed_kmh",
    "Visibility (km)": "visibility_km",
    "Pressure (millibars)": "pressure_mbar"})

# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Drop rows with invalid date
df = df.dropna(subset=['date'])

# Handle missing numeric values
num_cols = ['temp_c', 'feels_like_c', 'humidity', 'wind_speed_kmh', 'visibility_km', 'pressure_mbar']
df[num_cols] = df[num_cols].astype(float)

for col in num_cols:
  df[col] = df[col].fillna(df[col])

# Handle precipitation column
if "Precipitation (mm)" in df.columns:
    df = df.rename(columns={"Precipitation (mm)": "precip_mm"})
    df["precip_mm"] = pd.to_numeric(df["precip_mm"], errors="coerce").fillna(0.0)

"""**Descriptive statistics with NumPy**"""

# Convert columns to NumPy arrays
temp_arr = df['temp_c'].to_numpy()
hum_arr = df['humidity'].to_numpy()
precip_arr = df.get('precip_mm', pd.Series(0.0, index=df.index)).to_numpy()

def describe_array(arr, name):
  mean_ = np.mean(arr)
  median_ = np.median(arr)
  std_ = np.std(arr)
  print(f"{name} -> mean: {mean_: .2f}, median: {median_: .2f}, std: {std_: .2f}")

describe_array(temp_arr, "Temperature (C)")
describe_array(hum_arr, "Humidity")
describe_array(precip_arr, "Precipitation (mm)")

"""**Monthly and seasonal analysis (groupby)**"""

df['date'] = pd.to_datetime(df['date'], utc=True).dt.tz_localize(None)

# Add time‑based features
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

# define seasons (for Northern hemisphere)
def month_to_season(m):
  if m in [12, 1, 2]:
    return 'Winter'
  elif m in [3, 4, 5]:
    return 'Spring'
  elif m in [6, 7, 8]:
    return 'Summer'
  elif m in [9, 10, 11]:
    return 'Autumn'
  else:
    return 'Unknown'

df['season'] = df['month'].apply(month_to_season)

# Monthly averages
monthly_avg = df.groupby(['year', 'month'], as_index=False)[['temp_c', 'humidity']].mean()

# Seasonal averages
seasonal_avg = df.groupby('season', as_index=False)[['temp_c', 'humidity']].mean()

print(monthly_avg.head())
print(seasonal_avg)

"""**Visualizations with Matplotlib**

**Line plot – average temperature over time**
"""

# Aggregate to monthly mean for smoother trend
monthly_temp = df.resample("M", on="date")["temp_c"].mean()

plt.figure(figsize=(10, 4))
plt.plot(monthly_temp.index, monthly_temp.values, marker="o")
plt.title("Monthly Average Temperature Over Time")
plt.xlabel("Date")
plt.ylabel("Temperature (°C)")
plt.grid(True)
plt.tight_layout()
plt.savefig('temp_trend.png', dpi=150, bbox_inches='tight')
plt.show()

"""**Bar plot – precipitation by month**"""

# Average or total precipitation per calendar month across all years
monthly_rain_days = df.groupby("month")["precip_type"].apply(lambda x: (x == 'rain').sum())

plt.figure(figsize=(8, 4))
plt.bar(monthly_rain_days.index, monthly_rain_days.values, color="skyblue", edgecolor="black")
plt.title("Rainy Days by Month")
plt.xlabel("Month")
plt.ylabel("Number of Rainy Days")
plt.xticks(range(1, 13))
plt.grid(axis="y")
plt.tight_layout()
plt.savefig('rainy_days.png', dpi=150, bbox_inches='tight')
plt.show()

"""**Histogram – temperature distribution**"""

plt.figure(figsize=(8, 4))
plt.hist(df["temp_c"], bins=30, color="salmon", edgecolor="black")
plt.title("Temperature Distribution")
plt.xlabel("Temperature (°C)")
plt.ylabel("Frequency")
plt.grid(axis="y")
plt.tight_layout()
plt.savefig('temp_hist.png', dpi=150, bbox_inches='tight')
plt.show()

# Extreme weather analysis
hot_threshold = np.percentile(temp_arr, 90)
cold_threshold = np.percentile(temp_arr, 10)

print("Hot threshold (90th percentile):", hot_threshold)
print("Cold threshold (10th percentile):", cold_threshold)

# Boolean masks
hot_days_mask = temp_arr >= hot_threshold
cold_days_mask = temp_arr <= cold_threshold

hot_days = df[hot_days_mask]
cold_days = df[cold_days_mask]

print("Number of hot days:", hot_days.shape[0])
print("Number of cold days:", cold_days.shape[0])

# Inspect examples
print("\nHot days examples:")
print(hot_days[["date", "temp_c", "humidity"]].head())
print("\nCold days examples:")
print(cold_days[["date", "temp_c", "humidity"]].head())